#!/usr/bin/env python3
import sys

import pandas as pd
from jazzer_plot import parse_duration
import matplotlib.pyplot as plt


def main():
    if len(sys.argv) != 3:
        print("Usage: python libfuzzer_plot.py <stats.csv>")
        print("Example: python3 libfuzzer_plot.py targetA.csv")
        sys.exit(1)

    csv_file = parse_duration(sys.argv[1])

    df = pd.read_csv(csv_file)

    # plt.plot(crashes_timestamps, crashes_cnt, label="Jazzer Crashes")
    # plt.xlabel("Time (seconds)")
    # plt.ylabel("Crashes")
    # plt.legend()
    # plt.show()
    #
    # plt.plot(cov_timestamps, cov, label="Coverage")
    # plt.xlabel("Time (seconds)")
    # plt.ylabel("Coverage")
    # plt.legend()
    # plt.show()

    plt.plot(df['timestamp'], df['ft'], label="Features")
    plt.xlabel("Time (seconds)")
    plt.ylabel("Features")
    plt.legend()
    plt.show()

    pass


if __name__ == '__main__':
    main()
